##########################################################################################################
# If you want o support this repository I accept donations                                               #
# even 1 TOK is always welcome :-)!                                                                      #
# > ethereum address: 0x44F102616C8e19fF3FED10c0b05B3d23595211ce                                         #
# > tokugawa address: TjrQBaaCPoVW9mPAZHPfVx9JJCq7yZ7QnA                                                 #
#                                                                                                        #
#  Detalle de gastos acualizados (octubre)                                                               #
#    GastosMN1 =                                                                          #
#    GastosMN2 =                                                                     #
#                                                                                                        #
##########################################################################################################

#SECTION FOR BOT STYLE PARAMETERS
STYLE:
  FRAME:
    default_color:  0x00ff00
    error_color:    0xff0000

#SECTION FOR COIN SPECIFIC PARAMETERS
COIN:
    name:           Pirl
    acronym:        PIRL
    decimals:       2
    explorer_url:   none
    collateral:     20000

#SECTION FOR MASTERNODES
MASTERNODES:
    - name:           MN01
      setup_date:     initialdate
      setup_balance:  0
      explorin:       linkin1
      explorout:      linkout1
      explorbalance:  linkbalance1
      INVESTORS:
        - name:       name01
          coins:      0
        - name:       name02
          coins:      0
        - name:       name03
          coins:      0
        - name:       name04
          coins:      0
        - name:       name05
          coins:      0
        - name:       name06
          coins:      0
        - name:       name07
          coins:      0
      EXPENSES:
        - description: Gastos MN01 actualizados
          coins:       0
      operator:        0.0
    - name:           MN02
      setup_date:     initialdate
      setup_balance:  0
      explorin:       linkin2
      explorout:      linkout2
      explorbalance:  linkbalance2
      INVESTORS:
        - name:       name01
          coins:      0
        - name:       name02
          coins:      0
        - name:       name03
          coins:      0
        - name:       name04
          coins:      0
        - name:       name05
          coins:      0
        - name:       name06
          coins:      0
        - name:       name07
          coins:      0
      EXPENSES:
        - description: Gastos MN02 actualizados
          coins:       0
      operator:    0.0

#SECTION FOR DISCORD PARAMETERS
DISCORD:
     api_key: discord_api_key_bot
